// <auto-generated />
using AdminSolution.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AdminSolution.Migrations
{
    [DbContext(typeof(DbLayerContext))]
    [Migration("20180131105621_check")]
    partial class check
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminSolution.DataLayer.ClientContacts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("alternateNumber");

                    b.Property<string>("clientAddress");

                    b.Property<string>("clientName");

                    b.Property<string>("contactNumber");

                    b.Property<string>("emailAddress");

                    b.HasKey("ID");

                    b.ToTable("ClientContact");
                });

            modelBuilder.Entity("AdminSolution.DataLayer.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClientContactsID");

                    b.Property<string>("EventDate");

                    b.Property<string>("EventLocation");

                    b.Property<string>("EventType");

                    b.Property<string>("RequstedService");

                    b.HasKey("Id");

                    b.HasIndex("ClientContactsID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AdminSolution.DataLayer.Events", b =>
                {
                    b.HasOne("AdminSolution.DataLayer.ClientContacts", "ClientContacts")
                        .WithMany("Events")
                        .HasForeignKey("ClientContactsID");
                });
#pragma warning restore 612, 618
        }
    }
}
