// <auto-generated />
using AdminSolution.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AdminSolution.Migrations
{
    [DbContext(typeof(DbLayerContext))]
    [Migration("20180122063609_check1")]
    partial class check1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminSolution.DataLayer.ClientContacts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("alternateNumber");

                    b.Property<string>("clientAddress");

                    b.Property<string>("clientName");

                    b.Property<string>("contactNumber");

                    b.Property<string>("emailAddress");

                    b.HasKey("ID");

                    b.ToTable("ClientContact");
                });
#pragma warning restore 612, 618
        }
    }
}
